### PR TITLE
Feature/sentence fixed

### PR DESCRIPTION
**Pull request by Yuuki77**
solve a conflict

### CODE REVIEW

**Comment by ronkorving** [comment]
This PR fixes 2 things. Title change *and* sea-shore change. Was that your intention?

**Comment by Yuuki77** [comment]
It was . Was I wrong? I thought I have to do pull request twice. Fist is about 
title change and the last is about conflict...

**Comment by ronkorving** [comment]
But this "last PR", it also fixes the title. It's a combination of both fixes.
Look at your diff and the diff in #7 for example.

**Comment by AlmirKadric** [comment]
Apart from pollution of work, LGTM 👍

**Pull request closed without merging**
